export const AppRoute = {
  base: "/",
  root: "/shopkart",
  about: "/shopkart/about",
  contact: "/shopkart/contact",
  login: "/shopkart/login",
  logout: "/shopkart/logout",
  dashbaord: "/shopkart/dashboard",
  setting: "/shopkart/setting",
  configuration: "/shopkart/configuration",
  admin: "/shopkart/admin",
  adminDashboard: "/shopkart/admin/dashboard",
  adminUser: "/shopkart/admin/user",
  adminSize: "/shopkart/admin/size",
  adminColor: "/shopkart/admin/color",
  adminCategory: "/shopkart/admin/category",
  adminProduct: "/shopkart/admin/product",
  adminBrand: "/shopkart/admin/brand",
  adminStore: "/shopkart/admin/store",
  adminPage: "/shopkart/admin/page",
  notFound: "/shopkart/not-found",
};
