export enum Color {
  secondary = "secondary",
  gray = "gray",
  dark = "dark",
  primary = "primary",
  success = "success",
  info = "info",
  warning = "warning",
  danger = "danger",
  outlineSecondary = "outline-secondary",
  outlineInfo = "outline-info",
  outlinePrimary = "outline-primary",
  outlineSuccess = "outline-success",
  outlineWarning = "outline-warning",
  outlineDanger = "outline-danger",
  outlineDark = "outline-dark",
  outlineLight = "outline-light",
}
